apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api-gateway
  namespace: spring-petclinic
spec:
  endpoints:
  - port: http
    path: '/actuator/prometheus'
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app: api-gateway
